package debugui

const commonTemplate = `
{{define "head"}}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#121a2e;--line:#26324d;--muted:#91a0bb;--text:#eef3ff;--accent:#70a5ff;--good:#54d39a;--warn:#ffca6a;--bad:#ff7185}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}.wrap{max-width:1480px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:24px}.eyebrow{color:var(--accent);font-size:12px;letter-spacing:.16em;text-transform:uppercase}h1{margin:5px 0 0;font:700 28px/1.2 system-ui,sans-serif}h2{font:650 18px/1.2 system-ui,sans-serif}.muted{color:var(--muted)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;overflow:hidden}.toolbar{display:flex;gap:10px;align-items:end;margin:16px 0 20px}.toolbar label{display:grid;gap:5px;color:var(--muted)}input,select,button{border:1px solid var(--line);border-radius:7px;background:#0e1527;color:var(--text);padding:9px 11px;font:inherit}button,.button{display:inline-block;background:#1d3155;border:1px solid #35588e;border-radius:7px;color:var(--text);padding:9px 12px;cursor:pointer}table{width:100%;border-collapse:collapse}th,td{padding:12px 14px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}th{position:sticky;top:0;background:#172138;color:#aebbd1;font-size:11px;letter-spacing:.08em;text-transform:uppercase}tr:last-child td{border-bottom:0}.badge{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:2px 8px;font-size:12px}.badge.running{color:var(--warn)}.badge.completed{color:var(--good)}.badge.failed,.error{color:var(--bad)}.tabs{display:flex;gap:6px;margin:18px 0}.tabs a{border:1px solid var(--line);border-radius:7px;padding:8px 11px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.metric{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:15px}.metric .label{color:var(--muted);font-size:12px}.metric .value{font:650 21px/1.3 system-ui,sans-serif;margin-top:5px}.pager{display:flex;justify-content:space-between;margin-top:18px}.mono-break{word-break:break-all}.message{max-width:520px;white-space:pre-wrap}.empty{padding:36px;text-align:center;color:var(--muted)}
@media(max-width:850px){.wrap{padding:18px}.top{align-items:start;flex-direction:column}.panel{overflow:auto}th,td{white-space:nowrap}.message{white-space:normal;min-width:300px}}
</style>
{{end}}
{{define "runHeader"}}
<div class="top"><div><div class="eyebrow"><a href="/debug/">← All runs</a></div><h1 class="mono-break">{{.RunID}}</h1></div><div class="muted">Agent: {{.Run.AgentID}} / {{.Run.AgentVersion}}</div></div>
<nav class="tabs"><a href="/debug/runs/{{path .RunID}}/overview">Overview</a><a href="/debug/runs/{{path .RunID}}/logs">Logs</a></nav>
{{end}}
`

const runsTemplate = `<!doctype html><html><head><title>Simulation runs · Debug</title>{{template "head"}}</head><body><main class="wrap">
<div class="top"><div><div class="eyebrow">HackerSprint2 Simulator</div><h1>Run debug console</h1></div><div class="muted">Read-only event journal projections</div></div>
<form class="toolbar" method="get"><label>Agent ID<input name="agent_id" value="{{.AgentID}}" placeholder="all agents"></label><button type="submit">Filter</button>{{if .AgentID}}<a class="button" href="/debug/">Reset</a>{{end}}</form>
<section class="panel"><table><thead><tr><th>Run</th><th>Agent</th><th>State</th><th>Simulation time</th><th>Result</th><th>Storage</th></tr></thead><tbody>
{{range .Runs}}<tr><td><a href="/debug/runs/{{path .Run.RunID}}/overview">{{.Run.RunID}}</a><br><span class="muted">seed {{.Seed}} · {{timefmt .Run.CreatedAt}}</span></td><td>{{.Run.AgentID}}<br><span class="muted">{{.Run.AgentVersion}}</span></td><td>{{if .LoadError}}<span class="error">unavailable</span>{{else}}<span class="badge {{statusClass .Overview.RunStatus}}">{{.Overview.RunStatus}}</span><br><span class="muted">site {{.Overview.SiteStatus}}</span>{{end}}</td><td>{{if not .LoadError}}{{timefmt .Overview.SimulationTime}}<br><span class="muted">until {{timefmt .Overview.SimulationEndsAt}}</span>{{end}}</td><td>{{if .LoadError}}<span class="error">{{.LoadError}}</span>{{else}}{{minor .Overview.Costs.TotalCostMinor}} {{.Overview.Costs.Currency}} infrastructure cost{{end}}</td><td>{{.EventCount}} events<br><span class="muted">{{.AgentRequestCount}} agent requests</span></td></tr>{{else}}<tr><td class="empty" colspan="6">No runs found</td></tr>{{end}}
</tbody></table></section><div class="pager"><div>{{if .HasPrevious}}<a class="button" href="/debug/?agent_id={{query .AgentID}}&page={{.PreviousPage}}">← Previous</a>{{end}}</div><div>{{if .HasNext}}<a class="button" href="/debug/?agent_id={{query .AgentID}}&page={{.NextPage}}">Next →</a>{{end}}</div></div>
</main></body></html>`

const overviewTemplate = `<!doctype html><html><head><title>Overview · {{.RunID}}</title>{{template "head"}}</head><body><main class="wrap">{{template "runHeader" .}}
<section class="grid"><div class="metric"><div class="label">Run status</div><div class="value">{{.View.Overview.RunStatus}}</div></div><div class="metric"><div class="label">Site status</div><div class="value">{{.View.Overview.SiteStatus}}</div></div><div class="metric"><div class="label">Simulation time</div><div class="value">{{timefmt .View.Overview.SimulationTime}}</div><div class="muted">{{duration .View.Overview.Remaining}} remaining</div></div><div class="metric"><div class="label">Servers</div><div class="value">{{.View.Overview.ServerCount}}</div></div><div class="metric"><div class="label">Request error rate</div><div class="value">{{percent .View.Overview.ErrorRate}}</div></div><div class="metric"><div class="label">Infrastructure cost</div><div class="value">{{minor .View.Overview.Costs.TotalCostMinor}} {{.View.Overview.Costs.Currency}}</div></div><div class="metric"><div class="label">Agent requests</div><div class="value">{{.View.ActualAgentRequestCount}}</div></div><div class="metric"><div class="label">Actual wall-clock time</div><div class="value">{{duration .View.ActualWallClockRealTime}}</div></div></section>
<p class="muted">Target: uptime ≥ 99%, then minimum infrastructure cost. Uptime is calculated from simulated outage time; request error rate is diagnostic.</p>
</main></body></html>`

const logsTemplate = `<!doctype html><html><head><title>Logs · {{.RunID}}</title>{{template "head"}}</head><body><main class="wrap">{{template "runHeader" .}}
<form class="toolbar" method="get"><label>Status<select name="status"><option value="" {{if eq .Status 0}}selected{{end}}>All</option><option value="200" {{if eq .Status 200}}selected{{end}}>200</option><option value="500" {{if eq .Status 500}}selected{{end}}>500</option></select></label><button type="submit">Filter</button></form>
<section class="panel"><table><thead><tr><th>Timestamp</th><th>Request</th><th>Page</th><th>Status</th><th>Load / latency</th><th>Server</th><th>Error / message</th></tr></thead><tbody>{{range .View.Logs}}<tr><td>{{timefmt .Entry.Timestamp}}</td><td class="mono-break">{{.Entry.RequestID}}<br><span class="muted">{{.Entry.Source}}{{if .Entry.VisitorID}} · {{.Entry.VisitorID}}{{end}}</span></td><td>{{.Entry.Page}}{{if .Entry.ProductID}}<br><span class="muted">{{.Entry.ProductID}}</span>{{end}}</td><td>{{.Entry.StatusCode}}</td><td>{{.LoadUnits}} units<br><span class="muted">{{duration .Latency}}</span></td><td>{{if .ServerID}}{{.ServerID}}{{else}}—{{end}}</td><td class="message">{{if .Entry.ErrorCode}}<span class="error">{{.Entry.ErrorCode}}</span>{{end}}{{if .Entry.Message}}<br>{{.Entry.Message}}{{end}}</td></tr>{{else}}<tr><td class="empty" colspan="7">No matching logs</td></tr>{{end}}</tbody></table></section>{{if .NextQuery}}<div class="pager"><span></span><a class="button" href="?{{.NextQuery}}">Next 200 →</a></div>{{end}}
</main></body></html>`
